Add support for projects.getAncestry
googleapis/python-resource-manager pull request #10
Opened 2020-02-20 00:39 UTC by rvandegrift

The current `Project` implementation includes the immediate `parent` but provides no way to get the full ancestry.  This adds a property to expose that data.

2020-12-02 16:36 UTC, tseaver requested changes
Thanks for the patch!  In addition to my suggestions inline, I'm also ambivalent about having this as a property, rather than a method:  I would be inclined to spell it as `project.list_ancestors()'.  We don't use properties to wrap other API-invoking methods.  It would make documenting the return value clearer, as well.

2020-12-02 16:36 UTC, tseaver commented on google/cloud/resource_manager/project.py
> +        )
JSON is the default response type for `getAncestry`.
```suggestion
        resp = client._connection.api_request(
            method="POST", path='%s:getAncestry' % (self.path),
        )
```

2020-12-02 16:36 UTC, tseaver commented on tests/unit/test_project.py
> +
We also need a test for the case that the response is missing the `ancestor` key:
```suggestion
    def test_fetch_project_ancestry_hit(self):
        PROJECT_ID = 'project-id'
        GET_ANCESTRY_RESPONSE = {}

        connection = _Connection(GET_ANCESTRY_RESPONSE)
        client = _Client(connection=connection)
        project = self._make_one(PROJECT_ID, client)

        self.assertEqual(project.ancestry, [])
        
    def test_fetch_project_ancestry_hit(self):
        PROJECT_ID = 'project-id'
        ANCESTORS = [
                {'resourceId': {'type': 'project', 'id': PROJECT_ID}},
                {'resourceId': {'type': 'folder', 'id': '012345678901'}},
                {'resourceId': {'type': 'folder', 'id': '987654321098'}},
                {'resourceId': {'type': 'organization', 'id': '555555555555'}},
            ]
        GET_ANCESTRY_RESPONSE = {'ancestor': ANCESTORS}
        connection = _Connection(GET_ANCESTRY_RESPONSE)
        client = _Client(connection=connection)
        project = self._make_one(PROJECT_ID, client)

        self.assertEqual(project.ancestry, ANCESTORS)
```

2020-12-16 00:08 UTC, rvandegrift commented
@googlebot I fixed it.

2020-12-16 00:14 UTC, rvandegrift commented
@tseaver I've implemented your suggestions and rebased on master.  googlebot seems confused over my CLA status, I've confirmed the commits are all from my CLA-covered email.

2021-04-16 12:18 UTC, parthea commented
CLA looks good for @rvandegrift. @tseaver, please check CLA for your username.

2021-04-21 18:53 UTC, rvandegrift commented
I don't need this change anymore, we've opted to stick with the discovery api clients in most places to avoid these kinds of feature gaps.

2021-04-21 18:53 UTC, closed without merging